<?php include($viewFilesPath . '/Snippet/BoardHeader.phtml') ?>

<div id="inner">
<?php include($viewFilesPath . '/Snippet/BoardNavigation.phtml') ?>
<?php include($viewFilesPath . '/Snippet/PostForm.phtml') ?>

<?php if ($board->url == 'followedthreads') : ?>
<div class="board-additional-functions">
    <button class="button primary" onclick="markAllFollowedRead()"><?= _('Mark all as read') ?></button>
</div>
<?php endif ?>

<?php if (!empty($threads)) : ?>
    <?php foreach($threads as $thread) : ?>
    <div class="content-box thread" id="thread-<?= $thread->id ?>" data-id="<?= $thread->id ?>">
        <?php include($viewFilesPath . '/Snippet/ThreadSubject.phtml') ?>
        <div class="thread-content">
            <div class="post op-post<?= ($thread->userId==$user->id?' own-post':'') ?>" id="post-<?= $thread->id ?>" data-id="<?= $thread->id ?>">
                <?php $post = $thread; include($viewFilesPath . '/Snippet/Post.phtml') ?>
            </div>

            <?php include($viewFilesPath . '/Snippet/ThreadMeta.phtml') ?>
            <div class="replies">
            <?php if (!empty($thread->replies)) : ?>
                <?php if ($thread->replyCount > $config['view']['previewPosts']) : ?>
                <div class="replies-buttons">
                    <button class="link more-replies" onclick="getMoreReplies(<?= $thread->id ?>)"><?= _('show more replies') ?></button>
                    <button class="link less-replies" onclick="getMoreReplies(<?= $thread->id ?>)"><?= _('show less replies') ?></button>
                </div>
                <?php endif ?>
                <div class="more-replies-container"></div>
                <?php foreach($thread->replies as $reply) : ?>
                    <div class="post reply<?= ($reply->userId==$user->id?' own-post':'') ?>" id="post-<?= $reply->id ?>" data-id="<?= $reply->id ?>">
                        <?php $post = $reply; include($viewFilesPath . '/Snippet/Post.phtml') ?>
                    </div>
                <?php endforeach ?>
            <?php endif ?>
            </div>
            <div class="thread-buttons">
                <!--<a href="/<?= $board->url ?>/<?= $thread->id ?>"><?= _('Open thread') ?></a>-->
                <?php if (!$thread->locked || $user->isMod) : ?>
                <button class="link add-reply" data-thread="<?= $thread->id ?>"><?= _('reply') ?></button>
                <button class="link get-replies"><?= _('update') ?></button>
                <?php endif ?>
            </div>
        </div>
    </div>
    <?php endforeach; unset($thread); ?>
<?php else : ?>
    <div class="content-box">
        <h3><?= _('There are no threads here...') ?></h3>
    </div>
<?php endif ?>

<?php include($viewFilesPath . '/Snippet/BoardNavigation.phtml') ?>
</div>
