<?php include($viewFilesPath . '/Snippet/BoardHeader.phtml') ?>

<div id="inner">
<?php include($viewFilesPath . '/Snippet/BoardNavigation.phtml') ?>
<?php include($viewFilesPath . '/Snippet/PostForm.phtml') ?>

<?php if (!empty($threads)): ?>
<div class="board-additional-functions">
    <input type="text" id="search-catalog" placeholder="<?= _('Search threads...') ?>">
</div>
<div class="catalog">
    <?php foreach($threads as $thread): ?>
        <div class="post" id="thread-<?= $thread->id ?>" data-id="<?= $thread->id ?>">
            <?php include($viewFilesPath . '/Snippet/ThreadSubject.phtml') ?>
            <?php $post = $thread ?>
            <?php include($viewFilesPath . '/Snippet/PostButtons.phtml') ?>
            <figure class="post-file thumbnail">
                <a href="/<?= $board->url ?>/<?= $thread->id ?>">
                    <?php if (!empty($post->file)): ?>
                        <?php $src = $config['url']['files']. '/' . $post->file->folder . '/t/' . $post->file->name . '.jpg' ?>
                    <?php else: ?>
                        <?php $src = $config['url']['static'] . '/img/norppa_ylilauta.svg' ?>
                    <?php endif ?>
                    <img src="<?= $src ?>" alt="">
                </a>
            </figure>
            <blockquote class="message">
                <?= \YFW\Library\Text::formatMessage($post->message) ?>
            </blockquote>
            <?php include($viewFilesPath . '/Snippet/ThreadMeta.phtml') ?>
        </div>
    <?php endforeach; unset($thread); ?>
</div>
<?php else: ?>
<div class="content-box">
    <h3><?= _('There are no threads here...') ?></h3>
</div>
<?php endif ?>

<?php include($viewFilesPath . '/Snippet/BoardNavigation.phtml') ?>
</div>
