<?php include($viewFilesPath . '/Snippet/PageHeader.phtml') ?>

<div id="inner">
<script>
    (function() {
        var cx = '<?= $gCsePartnerPub ?>';
        var gcse = document.createElement('script');
        gcse.type = 'text/javascript';
        gcse.async = true;
        gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(gcse, s);
    })();
</script>
<gcse:searchresults-only></gcse:searchresults-only>
</div>
