<h3>
    <a href="/<?= $thread->boardUrl ?>/<?= $thread->id ?><?php
    if ($user->getThreadLastSeenReply($thread->id) !== null) :
        ?>#post-<?= $user->getThreadLastSeenReply($thread->id) ?><?php
    endif ?>"><?php if ($thread->sticky) :
        ?><span class="icon-pushpin icon" title="<?= _('Sticky') ?>"></span><?php
    endif;
    if ($thread->locked) :
        ?><span class="icon-lock icon" title="<?= _('Locked') ?>"></span><?php
    endif;
    ?><span class="subject"><?= htmlspecialchars($thread->subject) ?></span><?php
    if (!empty($user->getThreadUnreadCount($thread->id))) : ?>
        <span class="notification-count"><?= $user->getThreadUnreadCount($thread->id) ?></span>
    <?php endif ?>
    </a>
</h3>
