<div class="notifications-list">
    <?php if (empty($notifications['list'])): ?>
    <p><?= _('You don\'t have any notifications...') ?></p>
    <?php else: ?>
    <?php foreach ($notifications['list'] as $notification): ?>
    <div class="notification <?= (!$notification->isRead?'not-read':'is-read') ?>" id="n-<?= $notification->id ?>">
        <?php if (!empty($notification->postId)): ?>
            <a href="/post-<?= $notification->postId ?>"
                <?php if (!$notification->isRead): ?>
                    onclick="markNotificationRead(<?= $notification->id ?>, event)"
                <?php endif ?>>
                <?= htmlspecialchars(sprintf($notification->text, $notification->count)) ?>
            </a>
        <?php else: ?>
            <?= htmlspecialchars(sprintf($notification->text, $notification->count)) ?>
        <?php endif ?>
        <div class="notification-meta">
            <span class="datetime"><?= $notification->time ?></span>
            <?php if (!empty($notification->postId)): ?>
                <a href="/post-<?= $notification->postId ?>" class="ref"
                   <?php if (!$notification->isRead): ?>
                       onclick="markNotificationRead(<?= $notification->id ?>, event)"
                   <?php endif ?>
                   data-id="<?= $notification->postId ?>">&gt;&gt;<?= $notification->postId ?></a>
            <?php endif ?>
        </div>
        <?php if (!$notification->isRead): ?>
        <button class="e-mark-read icon-checkmark-circle" data-id="<?= $notification->id ?>"></button>
        <?php endif ?>
    </div>
    <?php endforeach ?>
    <?php endif ?>
</div>
<div class="buttons">
    <button class="button primary close-modal e-mark-all-read"><?= _('Mark all as read') ?></button>
</div>
