<!doctype html>
<html>
<head>
    <title><?= htmlspecialchars($this->getTitle($config['app']['name'])) ?></title>

    <meta charset="UTF-8">

    <meta name="robots" content="index, follow">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="<?= $stylesheet['color'] ?>">

    <base href="<?= $config['app']['url'] ?>">

    <link rel="stylesheet" class="css" href="<?= $config['app']['staticUrl'] . $stylesheet['active'] ?>?<?=time()?>"
          data-light="<?= $config['app']['staticUrl'] . $stylesheet['light'] ?>?<?=time()?>"
          data-dark="<?= $config['app']['staticUrl'] . $stylesheet['dark'] ?>?<?=time()?>"
          data-darkTheme="<?= $stylesheet['darkTheme'] ?>">
    <?php if ($user->preferences->hideSidebar): ?>
    <link rel="stylesheet" id="hide-sidebar" href="<?= $config['app']['staticUrl'] ?>/css/hide_sidebar.css">
    <?php endif ?>

    <link rel="icon" sizes="192x192" href="<?= $config['app']['staticUrl'] . $config['app']['logoUrl'] ?>">

    <script src="<?= $config['app']['staticUrl'] ?>/js/locales/<?= $locale['name'] . '.' . $locale['domain'] ?>.js" defer></script>
    <script src="<?= $config['app']['staticUrl'] ?>/js/config.js" defer></script>
    <script src="<?= $config['app']['staticUrl'] ?>/js/yboard.js?<?=time()?>" defer></script>

    <script>let csrfToken='<?= $user->session->csrfToken ?>';</script>

    <?php if ($config['captcha']['enabled'] && $user->requireCaptcha): ?>
    <script>function renderCaptchas(){YBoard.Captcha.renderAll();}</script>
    <script src="https://www.google.com/recaptcha/api.js?onload=renderCaptchas&render=explicit" async defer></script>
    <?php endif ?>
</head>
<body<?= (!empty($bodyClass)?' class="' . $bodyClass . '"':'') ?>>

<div id="topbar">
    <button class="sidebar-toggle"><span class="icon-menu"></span><?= _('Menu') ?></button>
    <div class="buttons"
        ><button id="notifications-button" class="icon-alarm" title="<?= _('Notifications') ?>"
            ><span class="unread-notifications unread-count red<?= ($user->notifications->unreadCount==0?' none':'') ?>"
            ><?= $user->notifications->unreadCount ?></span></button
        ><a href="/followedthreads/" class="icon-bookmark2" title="<?= _('Followed threads') ?>"><?php
            if($user->threadFollow->unreadCount != 0) :
                ?><span class="unread-count green"><?= $user->threadFollow->unreadCount ?></span><?php
            endif ?></a
        ><button id="scroll-to-bottom" class="icon-enter-down2" title="<?= _('Go to bottom') ?>"></button
        ><button id="scroll-to-top" class="icon-enter-up2" title="<?= _('Back to top') ?>"></button
        ><button id="reload-page" class="icon-sync" title="<?= _('Refresh page') ?>"></button
    ></div>
</div>

<?php include($viewFilesPath . '/Snippets/Sidebar.phtml') ?>

<div id="content">
    <?php if ($user->ban) : ?>
    <div id="banned">
        <h3><?= _('You are banned!') ?></h3>
        <p>
            <?= sprintf(_('Reason: %s'), $user->ban->getReasonText()) ?>
            <?= (empty($user->ban->additionalInfo)?'':', ' . $user->ban->additionalInfo) ?>
        </p>
        <p>
            <?= sprintf(_('Your ban ends: %s'), '<span class="datetime">' . $user->ban->endTime . '</span>') ?>
        </p>
        <?php if ($user->ban->messageFrom): ?>
            <p class="tooltip" title="<?= htmlspecialchars($user->ban->messageFrom) ?>"
            ><?= _('Click here to see the post that resulted in this ban.') ?></p>
        <?php endif ?>
        <?php if ($user->ban->userId != $user->id): ?>
        <p><?= _('This ban was not given to your user account, but to someone near you.') ?></p>
        <?php endif ?>
    </div>
    <?php endif ?>
    <?= $output ?>
</div>
<div id="modal-root"></div>
</body>
</html>
