<?php header('Content-Type: text/html; charset=utf-8'); ?>
<!doctype html>
<html>
<head>
    <title><?= htmlspecialchars($this->getTitle()) ?></title>

    <meta charset="UTF-8">

    <meta name="robots" content="index, follow">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#117743">

    <base href="<?= $baseUrl ?>">

    <link rel="stylesheet" class="css" href="<?= $staticUrl ?>/css/<?= $stylesheet ?>.css?<?=time()?>"
          data-alt="<?= $staticUrl ?>/css/<?= $altStylesheet ?>.css?<?=time()?>">
    <?php if ($user->preferences->hideSidebar): ?>
    <link rel="stylesheet" id="hide-sidebar" href="<?= $staticUrl ?>/css/hide_sidebar.css">
    <?php endif ?>

    <link rel="icon" sizes="192x192" href="<?= $staticUrl ?>/img/norppa_icon.png">

    <!--<script src="<?= $staticUrl ?>/js/jquery.min.js" defer></script>
    <script src="<?= $staticUrl ?>/js/toastr.min.js" defer></script>
    <script src="<?= $staticUrl ?>/js/tooltipster.min.js" defer></script>-->
    <script src="<?= $staticUrl ?>/js/locales/<?= $locale . '.' . $localeDomain ?>.js" defer></script>
    <script src="<?= $staticUrl ?>/js/yboard.js?<?=time()?>" defer></script>

    <script>
        var config = {
            staticUrl: '<?= $staticUrl ?>',
            csrfToken: '<?= $csrfToken ?>',
            reCaptchaPublicKey: '<?= $reCaptchaPublicKey ?>',
        };
    </script>

    <?php if ($user->requireCaptcha): ?>
    <script src="https://www.google.com/recaptcha/api.js?onload=renderCaptcha&render=explicit" async defer></script>
    <?php endif ?>
</head>
<body<?= (!empty($bodyClass)?' class="' . $bodyClass . '"':'') ?>>

<div id="topbar">
    <button class="sidebar-toggle"><span class="icon-menu"></span><?= _('Menu') ?></button>
    <div class="buttons"
        ><button id="notifications-button" onclick="getNotifications()" class="icon-alarm" title="<?= _('Notifications') ?>"
            ><span class="unread-notifications unread-count red<?= ($user->notifications->unreadCount==0?' none':'') ?>"
            ><?= $user->notifications->unreadCount ?></span></button
        ><a href="/followedthreads/" class="icon-bookmark2" title="<?= _('Followed threads') ?>"><?php
            if($user->threadFollow->unreadCount != 0) :
                ?><span class="unread-count green"><?= $user->threadFollow->unreadCount ?></span><?php
            endif ?></a
        ><button onclick="$(document).scrollTop($('body').height())" class="icon-enter-down2" title="<?= _('Go to bottom') ?>"></button
        ><button onclick="$(document).scrollTop(0)" class="icon-enter-up2" title="<?= _('Back to top') ?>"></button
        ><button onclick="pageReload()" class="icon-sync" title="<?= _('Refresh page') ?>"></button
    ></div>
</div>

<?php include($viewFilesPath . '/Snippets/Sidebar.phtml') ?>

<div id="content">
    <?php if ($user->ban) : ?>
    <div id="banned">
        <h3><?= _('You are banned!') ?></h3>
        <p>
            <?= sprintf(_('Reason: %s'), $user->ban->getReasonText()) ?>
            <?= (empty($user->ban->additionalInfo)?'':', ' . $user->ban->additionalInfo) ?>
        </p>
        <p>
            <?= sprintf(_('Your ban ends: %s'), '<span class="datetime">' . $user->ban->endTime . '</span>') ?>
        </p>
        <?php if ($user->ban->messageFrom): ?>
            <p class="tooltip" title="<?= htmlspecialchars($user->ban->messageFrom) ?>"
            ><?= _('Click here to see the post that resulted in this ban.') ?></p>
        <?php endif ?>
        <?php if ($user->ban->userId != $user->id): ?>
        <p><?= _('This ban was not given to your user account, but to someone near you.') ?></p>
        <?php endif ?>
    </div>
    <?php endif ?>
    <?= $output ?>
</div>
<div id="modal-root"></div>
</body>
</html>
